Fixed JavaScript Error for the SubmitButtons while using CreditCard
mollie/Shopware pull request #35
Opened 2020-09-08 08:32 UTC by alphanyx

The Default Shopware Checkout has 2 "submit" Buttons.
One above the Shipping and Payment Methods and one below.

If CreditCard ist the first selected Component while opening the checkout, the JavaScript that selects the Submit button is executed directly instead of waiting until the DOM is ready.

In the default checkout this works because we have a submit button that was printed into the dom before the javascript was executed.

Customized Checkouts with only one submit button below the payment and shipping selection will cause an JavaScript Error:

components?ext=.js&ts=1599553913:69 Uncaught (in promise) TypeError: Cannot set property 'disabled' of null
    at disableForm (components?ext=.js&ts=1599553913:69)
    at HTMLFormElement.<anonymous> (components?ext=.js&ts=1599553913:112)

This pull request solves the problem by selecting the submit buttons on the click and selecting all buttons instead of the first found one.
This method also throws no error if no submit button was found

2020-09-21 10:46 UTC, barbieswimcrew requested changes

2020-09-21 10:46 UTC, barbieswimcrew commented on Resources/views/frontend/_public/src/js/components.js
> +        if (submitButtons.length) {
please modify your condition like following to avoid possible implicit typecast issues

`if (submitButtons.length > 0) `

2020-09-21 10:46 UTC, barbieswimcrew commented on Resources/views/frontend/_public/src/js/components.js
> +        if (submitButtons.length) {
please modify your condition like following to avoid possible implicit typecast issues

if (submitButtons.length > 0)

2020-09-22 08:11 UTC, boxblinkracer commented
hey great work, thanks for providing that fix
looking forward to it when its merged after the changes requested by @barbieswimcrew  :)

2020-09-23 10:17 UTC, barbieswimcrew approved these changes

2020-09-23 10:18 UTC, merged